In [1]:
import torch
import numpy as np

In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2541, 0.9022],
        [0.9291, 0.8889]]) 



In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1828, 0.4029, 0.0561],
        [0.4103, 0.1151, 0.0151]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [10]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.1124, 0.8715, 0.8672, 0.4548])
First column: tensor([0.1124, 0.3383, 0.2858, 0.1790])
Last column: tensor([0.4548, 0.6319, 0.5010, 0.7521])
tensor([[0.1124, 0.0000, 0.8672, 0.4548],
        [0.3383, 0.0000, 0.3864, 0.6319],
        [0.2858, 0.0000, 0.6157, 0.5010],
        [0.1790, 0.0000, 0.6367, 0.7521]])


In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.1124, 0.0000, 0.8672, 0.4548, 0.1124, 0.0000, 0.8672, 0.4548, 0.1124,
         0.0000, 0.8672, 0.4548],
        [0.3383, 0.0000, 0.3864, 0.6319, 0.3383, 0.0000, 0.3864, 0.6319, 0.3383,
         0.0000, 0.3864, 0.6319],
        [0.2858, 0.0000, 0.6157, 0.5010, 0.2858, 0.0000, 0.6157, 0.5010, 0.2858,
         0.0000, 0.6157, 0.5010],
        [0.1790, 0.0000, 0.6367, 0.7521, 0.1790, 0.0000, 0.6367, 0.7521, 0.1790,
         0.0000, 0.6367, 0.7521]])


Nella seguente cella si vedono diversi modi per ottenere una moltiplicazionme matriciale ed una moltiplicazione elemento per elemento: y1=y2=y3 e z1=z2=z3

In [12]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0126, 0.0000, 0.7520, 0.2069],
        [0.1145, 0.0000, 0.1493, 0.3993],
        [0.0817, 0.0000, 0.3791, 0.2510],
        [0.0320, 0.0000, 0.4054, 0.5656]])

In [15]:
agg = tensor.sum()
agg_item = agg.item() # gets the value of a tensor as a standard Python number
print(agg_item, type(agg_item))
print(agg, type(agg))

5.761419773101807 <class 'float'>
tensor(5.7614) <class 'torch.Tensor'>


In [16]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.1124, 0.0000, 0.8672, 0.4548],
        [0.3383, 0.0000, 0.3864, 0.6319],
        [0.2858, 0.0000, 0.6157, 0.5010],
        [0.1790, 0.0000, 0.6367, 0.7521]]) 

tensor([[5.1124, 5.0000, 5.8672, 5.4548],
        [5.3383, 5.0000, 5.3864, 5.6319],
        [5.2858, 5.0000, 5.6157, 5.5010],
        [5.1790, 5.0000, 5.6367, 5.7521]])


### Tensor <-> Numpy

In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Changes in the NumPy array reflects in the tensor.

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
